# Generated by Django 3.1.6 on 2022-03-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='nodeuser',
            managers=[
            ],
        ),
    ]
