# Generated by Django 3.1.6 on 2022-03-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='comments',
            field=models.ManyToManyField(to='backend.Comment'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='follows',
            field=models.ManyToManyField(to='backend.Follow'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='likes',
            field=models.ManyToManyField(to='backend.Like'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-03-30T17:10:39+00:00', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-03-30T17:10:39+00:00', editable=False),
        ),
    ]
