<<<<<<<< HEAD:backend/migrations/0002_auto_20220320_2041.py
# Generated by Django 3.1.6 on 2022-03-21 02:41
========
# Generated by Django 3.1.6 on 2022-03-21 02:18
>>>>>>>> apiv2:backend/migrations/0002_auto_20220320_2018.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
<<<<<<<< HEAD:backend/migrations/0002_auto_20220320_2041.py
            field=models.DateTimeField(default='2022-03-21T02:41:13+00:00', editable=False),
========
            field=models.DateTimeField(default='2022-03-21T02:18:20+00:00', editable=False),
>>>>>>>> apiv2:backend/migrations/0002_auto_20220320_2018.py
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
<<<<<<<< HEAD:backend/migrations/0002_auto_20220320_2041.py
            field=models.DateTimeField(default='2022-03-21T02:41:13+00:00', editable=False),
========
            field=models.DateTimeField(default='2022-03-21T02:18:20+00:00', editable=False),
>>>>>>>> apiv2:backend/migrations/0002_auto_20220320_2018.py
        ),
    ]
