# Generated by Django 3.1.6 on 2022-03-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.comment'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='follows',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.follow'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.like'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-03-30T15:58:33+00:00', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-03-30T15:58:33+00:00', editable=False),
        ),
    ]
