# Generated by Django 4.0.2 on 2022-04-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_comment_published_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-04-04T00:33:10+00:00', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-04-04T00:33:10+00:00', editable=False),
        ),
    ]
