# Generated by Django 3.1.6 on 2022-04-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220404_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-04-04T16:19:45+00:00', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-04-04T16:19:45+00:00', editable=False),
        ),
    ]
