# Generated by Django 3.2.12 on 2022-04-04 17:12

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220402_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=backend.models.post_img_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image_id',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-04-04T17:12:37+00:00', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-04-04T17:12:37+00:00', editable=False),
        ),
    ]
