# Generated by Django 3.1.6 on 2022-04-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220401_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-04-02T00:07:27+00:00', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-04-02T00:07:27+00:00', editable=False),
        ),
    ]
