# Generated by Django 3.1.6 on 2022-04-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220404_1019'),
        ('backend', '0004_auto_20220404_1712'),
    ]

    operations = [
    ]
