# Generated by Django 3.1.6 on 2022-03-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220323_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='api_prefix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-03-23T20:28:47+00:00', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-03-23T20:28:47+00:00', editable=False),
        ),
    ]
