# Generated by Django 3.1.6 on 2022-03-21 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20220320_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-03-21T02:19:49+00:00', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-03-21T02:19:49+00:00', editable=False),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('object', models.URLField(blank=True, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.author')),
            ],
        ),
    ]
