# Generated by Django 3.1.6 on 2022-03-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20220322_0211'),
        ('backend', '0005_auto_20220320_2019'),
    ]

    operations = [
    ]
