# Generated by Django 3.1.6 on 2022-03-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220320_2019'),
        ('backend', '0008_auto_20220322_0236'),
    ]

    operations = [
    ]
