# Generated by Django 3.1.6 on 2022-03-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20220322_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('api_domain', models.URLField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-03-22T09:09:55+00:00', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-03-22T09:09:55+00:00', editable=False),
        ),
    ]
