# Generated by Django 3.1.6 on 2022-03-01 10:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('de2aead7-bc3b-4550-a047-35d36a2a5c73'), primary_key=True, serialize=False),
        ),
    ]
