# Generated by Django 3.1.6 on 2022-02-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeuser',
            name='display_name',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='nodeuser',
            name='id',
            field=models.URLField(),
        ),
    ]
