# Generated by Django 3.1.6 on 2022-02-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeuser',
            name='id',
            field=models.URLField(editable=False),
        ),
    ]
