# Generated by Django 3.1.6 on 2022-02-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
