# Generated by Django 3.1.6 on 2022-03-01 10:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220301_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fa3408a0-39f1-44c8-bd0c-f6f67107bdc6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nodeuser',
            name='id',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
