# Generated by Django 3.1.6 on 2022-02-23 05:14

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_nodeuser_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeuser',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nodeuser',
            name='uuid_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
