# Generated by Django 3.1.6 on 2022-02-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220226_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.URLField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
