# Generated by Django 3.1.6 on 2022-02-25 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220224_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeuser',
            name='followers',
            field=models.ManyToManyField(related_name='_nodeuser_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
