# Generated by Django 4.0.2 on 2022-03-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_comment_published_alter_nodeuser_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-03-04T18:52:14+00:00'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-03-04T18:52:14+00:00'),
        ),
    ]
