# Generated by Django 3.1.6 on 2022-03-02 02:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220301_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeuser',
            name='account_activated',
        ),
        migrations.AlterField(
            model_name='like',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c0aed130-921d-409e-a375-f10df7f32521'), primary_key=True, serialize=False),
        ),
    ]
