# Generated by Django 3.2.12 on 2022-03-04 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_comment_published_alter_nodeuser_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-03-04T15:16:41+00:00'),
        ),
        migrations.AlterField(
            model_name='nodeuser',
            name='followers',
            field=models.ManyToManyField(related_name='_accounts_nodeuser_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-03-04T15:16:41+00:00'),
        ),
    ]
