# Generated by Django 3.1.6 on 2022-02-25 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220225_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeuser',
            name='followers',
            field=models.ManyToManyField(db_constraint=False, related_name='_nodeuser_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
