# Generated by Django 3.1.6 on 2022-03-02 04:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220301_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-03-02T04:51:09+00:00'),
        ),
        migrations.AlterField(
            model_name='like',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6114bbe9-d723-4f2f-82d5-dcbedcaff2a9'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-03-02T04:51:09+00:00'),
        ),
    ]
