# Generated by Django 3.1.6 on 2022-03-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220304_1315'),
        ('accounts', '0007_auto_20220304_1829'),
    ]

    operations = [
    ]
