# Generated by Django 4.0.2 on 2022-03-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_comment_published_alter_post_published'),
        ('accounts', '0007_auto_20220304_1829'),
    ]

    operations = [
    ]
