# Generated by Django 3.1.6 on 2022-03-18 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220304_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeuser',
            name='author_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-03-18T07:40:19+00:00'),
        ),
        migrations.AlterField(
            model_name='nodeuser',
            name='id',
            field=models.URLField(blank=True, default=uuid.uuid4, max_length=255, null=True, unique=True, verbose_name='url_id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-03-18T07:40:19+00:00'),
        ),
    ]
