# Generated by Django 3.1.6 on 2022-03-18 07:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220318_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2022-03-18T07:41:27+00:00'),
        ),
        migrations.AlterField(
            model_name='nodeuser',
            name='id',
            field=models.URLField(blank=True, default=uuid.uuid4, max_length=255, unique=True, verbose_name='url_id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2022-03-18T07:41:27+00:00'),
        ),
    ]
