# Generated by Django 3.1.6 on 2022-03-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220318_0200'),
        ('accounts', '0011_auto_20220318_0214'),
    ]

    operations = [
    ]
